language: php
php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source
    - composer create-project --no-interaction jakub-onderka/php-parallel-lint php-parallel-lint ~0.9
    - composer create-project --no-interaction nette/code-checker code-checker ~2.5.0

script:
    - php php-parallel-lint/parallel-lint.php -e php src
    - php php-parallel-lint/parallel-lint.php -e php,phpt tests
    - php code-checker/src/code-checker.php --short-arrays -d src
    - php code-checker/src/code-checker.php --short-arrays -d tests
    - vendor/bin/tester -p php -c tests/php.ini tests
